services:
  hytale:
    image: ocelus/hytale-docker-server:latest
    container_name: hytale
    ports:
      - "5520:5520/udp"
    environment:
      - ENABLE_SENTRY=true
    volumes:
      - hytale-data:/game
    restart: unless-stopped

volumes:
  hytale-data: