services:
  hytale:
    image: ocelus/hytale-docker-server:latest
    container_name: hytale
    ports:
      - "5520:5520/udp"
    environment:
      - XMX=8G
      - XMS=4G
      - GC_TYPE=zgc
      - USE_AOT=true
    volumes:
      - hytale-data:/game
    restart: unless-stopped

volumes:
  hytale-data: